FROM python:3.9-slim

WORKDIR /app

# Install system dependencies for Postgres
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ .

# Expose Prometheus Metrics Port
EXPOSE 8000

CMD ["python", "coordinator.py"]